server: 
  port : 8084

spring:
  application:
    name: DC-API
  boot:
    admin:
      client:
        url: http://localhost:1111/
  config:
    import: optional:configserver:http://localhost:2222
    
  datasource:
    userName: root
    password: Password1
    url: jdbc:mysql://localhost:3306/his?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: '*'

